// <auto-generated />
using CodingCafeV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingCafeV2.Migrations
{
    [DbContext(typeof(CafeContext))]
    [Migration("20231209041420_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodingCafeV2.Models.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "100 Cafe Circle",
                            City = "Traverse City",
                            Email = "jacksmith@gmail.com",
                            FirstName = "Jack",
                            LastName = "Smith",
                            Phone = "1234567890",
                            State = "MI",
                            Zip = "49684"
                        },
                        new
                        {
                            ID = 2,
                            Address = "100 Cafe Circle",
                            City = "Traverse City",
                            Email = "jillsmith@gmail.com",
                            FirstName = "Jill",
                            LastName = "Smith",
                            Phone = "1234567891",
                            State = "MI",
                            Zip = "49684"
                        },
                        new
                        {
                            ID = 3,
                            Address = "123 Apple Way",
                            City = "Detroit",
                            Email = "stevejobs@gmail.com",
                            FirstName = "Steve",
                            LastName = "Jobs",
                            Phone = "1234567892",
                            State = "MI",
                            Zip = "56476"
                        },
                        new
                        {
                            ID = 4,
                            Address = "456 Microsoft Ln",
                            City = "Grand Rapids",
                            Email = "billgates@gmail.com",
                            FirstName = "Bill",
                            LastName = "Gates",
                            Phone = "234567893",
                            State = "MI",
                            Zip = "44455"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
